services:
  - type: web
    name: sylanty
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SYLANTY_SECRET
        generateValue: true
